### ISSUE TITLE
Discharge Function

### ISSUE THREAD

**Issue by mackerman44** [BiomarkABS/DASH#10]
We need to create a function that calculated discharge and any location where those measurements were made.

Here is a description of Discharge (Q), which I grabbed, that I believe is from the CHaMP metric dictionary:

The sum of station discharge across all stations. Station discharge is calculated as depth x velocity x station increment for all stations except first and last. Station discharge for the first and last station is 0.5 x station width x depth x velocity.

**Comment by KevinSee** [comment]
I created a function, calc_discharge to do this. I found the CHaMP calculations here: https://www.monitoringresources.org/Document/Method/Details/853, and based it on that.
