### ISSUE TITLE
QC for Pebble Values

### ISSUE THREAD

**Issue by mackerman44** [BiomarkABS/DASH#26]
Need to add a QC to `qc_cu()` to check that pebble values match expected. Should be able to get the expected values from Richie and/or the DASH protocol. Just a reminder.

**Comment by KevinSee** [comment]
In the qc_scripts branch, I added a function called `qc_cu_v2()` that includes this functionality, but it still needs final values to use for min/max pebble sizes. That function also moved a lot of the QC values that are being checked against into arguments, with default values so they can more easily be altered if need be in the future.

**Comment by KevinSee** [comment]
The pull request #29 dealt with this issue by including a QC as part of the `qc_cu()` function for pebble size being between a min and max value, which are arguments to the `qc_cu()` function.
