### ISSUE TITLE
Grouse 2020 CU table has multiple parent global IDs

### ISSUE THREAD

**Issue by KevinSee** [BiomarkABS/DASH#41]
The first 34 channel units in the CU_1.csv file have the same parent global ID, which matches a global ID in surveyPoint_0.csv. After that the parent global IDs start increasing by 1 in the last few digits every channel unit. None of those have a match in the surveyPoint_0.csv file, so the channel unit rollup ends up with NAs in several columns for those channel units, including site name, survey date, etc. 

@rcarmichael3, any thoughts about why this might happen? Should someone go into the CU_1.csv file and manually change all those parent global IDs to match the first 34?

**Comment by mackerman44** [comment]
I just went into 2_qcd_csvs/Grouse_Survey123_2020/CU_1.csv and made all parent global IDs match the first 34 and the global ID in surveyPoint_0.csv. Seems like a very safe bet.

This seems like the result of an auto-fill feature in Excel. If you use the autofill in Excel, it will automatically increment each cell by 1 if your cell contents ends with a number. I suspect someone tried to use that feature to make all of the parent global IDs match, but they accidentally ended up being sequential. Perhaps somebody reviewing the Secesh data after getting back from the field?

**Comment by mackerman44** [comment]
I added checks to both qc_cu() and qc_disch() to flag any path_nms with multiple ParentGlobalIDs. In both those cases, we'd expect only one. But we'll want to re-run on all 2019 and 2020 data.

**Comment by mackerman44** [comment]
I re-ran on all data. There was also an issue with multiple ParentGlobalIDs in the Discharge_5.csv file for 2_qcd_csvs/Grouse_Survey123_2020/Discharge_5.csv.

Closing this Issue.
